server:
  port: 9090
spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/mytestrealm
          jwk-set-uri: http://localhost:8180/auth/realms/mytestrealm/protocol/openid-connect/certs

module-name: mymodule
api-version: 1.0

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger-test
      clientSecret: 066fc52b-d6f4-46b0-a9da-7dedcb3421f0

  oAuthFlow:
    authorizationUrl: http://localhost:8180/auth/realms/mytestrealm/protocol/openid-connect/auth
    tokenUrl: http://localhost:8180/auth/realms/mytestrealm/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true






